### PR TITLE
fix: Improve background script detection logic for analytics package

### LINKED ISSUE #1807: @wxt-dev/analytics | Firefox MV2 & MV3 | createBackgroundAnalytics execution skipped
### Describe the bug

I'm trying to forward analytics events to the background script but I get the following error

Image

### Reproduction

You can use my repo to check https://github.com/sm17p/amgiflol

### Steps to reproduce

1. Create `app.config.ts` and setup analytics using `defineAppConfig`
2. Run pnpm dev:firefox

### System Info

```shell
System:
    OS: macOS 15.5
    CPU: (8) arm64 Apple M2
    Memory: 79.66 MB / 16.00 GB
    Shell: 4.0.2 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 24.1.0 
    npm: 11.3.0 
    pnpm: 10.12.3 
  Browsers:
    Chrome: 138.0.7204.101
    Firefox: 140.0.4
  npmPackages:
    wxt: ^0.20.6 => 0.20.7
```

### Used Package Manager

pnpm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://wxt.dev/guide/installation.html).
- [x] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sm17p**
### Overview

My attempt to resolve backgroundScript detection logic for analytics module based on 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_support

### Manual Testing

I'm going to add this soon

### Related Issue

This PR closes #1807

### CODE REVIEW

File: packages/analytics/modules/analytics/client.ts [hunk 1]
```diff
@@ -13,6 +13,40 @@ import { browser } from '@wxt-dev/browser';
...
+
+  const { background, background_page: backgroundPageWXT, manifest_version } = browser.runtime.getManifest();
+  // Misonfiguration or Non-WXT Contenxt Check
+  // Force check page attribute for possible configurations
+  const backgroundPageManifest = (background as any)?.page;
+
+  const backgoundPageorScriptsCheck =
+    location.pathname === '/_generated_background_page.html' ||
+    (backgroundPageManifest && location.pathname.endsWith(backgroundPageManifest)) ||
+    (backgroundPageWXT && location.pathname.endsWith(backgroundPageWXT));
```
Comment (sm17p) [inline packages/analytics/modules/analytics/client.ts]: I need help over here. I couldn't find `background_page` property on the manifest anywhere, so I'm not sure if this internal and needs to be checked

File: packages/analytics/modules/analytics/client.ts [hunk 2]
```diff
@@ -13,6 +13,37 @@ import { browser } from '@wxt-dev/browser';
...
+    return false;
+  }
+
+  const { background, background_page: backgroundPageWXT, manifest_version } = browser.runtime.getManifest();
+  // Misconfiguration or Non-WXT Context Check
+  // Force check page attribute for possible configurations
+  const backgroundPageManifest = (background as any)?.page;
+
+  const backgroundPageOrScriptsCheck =
+    location.pathname === '/_generated_background_page.html' ||
```
Comment (aklinker1) [inline packages/analytics/modules/analytics/client.ts]: Where is this string coming from?

File: packages/analytics/modules/analytics/client.ts (hunk 1 above)
Comment (aklinker1) [reply packages/analytics/modules/analytics/client.ts]: Not sure where you found this property in the first place... Isn't it `background.page`?

File: packages/analytics/modules/analytics/client.ts (hunk 2 above)
Comment (sm17p) [reply packages/analytics/modules/analytics/client.ts]: I found it in source code of browsers

1. https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/chromium/chromium%24+_generated_background_page.html&patternType=keyword&sm=0
2. https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/mozilla-firefox/firefox%24++_generated_background_page.html&patternType=keyword&sm=0
3. https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/WebKit/WebKit%24+_generated_background_page.html&patternType=keyword&sm=0

File: packages/analytics/modules/analytics/client.ts (hunk 1 above)
Comment (sm17p) [reply packages/analytics/modules/analytics/client.ts]: Yes, you are right. I earlier thought that having `background_page` set in the manifest would generate `_generated_background_page.html` but it's  actually when you only specify '.js' files in the scripts

**Comment by sm17p** [comment]
Anything pending from my side or any blockers to get this merged?

**Comment by PatrykKuniczak** [comment]
@sm17p I'm not familiar with with PR, but if you want to get this merged, let's make sure, you've done all necessary request changes, then resolve those conversations, and then assign @aklinker1 one more time, because he has notification only for assing him on comments :)

And resolve conflicts

**Comment by aklinker1** [comment]
I've pulled this out into a separate package, `@wxt-dev/is-background` (added @sm17p as a contributor on that PR as well), because this logic is useful for more than just the analytics package. Was able to simplify it a bit as well. Confirmed to be working on Chrome, Firefox, and Safari, MV2 and MV3.

Once that PR merged and released, we can pull it into the analytics package.

**Comment by aklinker1** [comment]
Alright, it's merged and live on NPM: https://github.com/wxt-dev/wxt/releases/tag/is-background-v1.0.0

**Comment by sm17p** [comment]
Thanks for this @PatrykKuniczak @aklinker1. Appreciate all the effort!
