### PR TITLE
fix: Scripts injection for content-scripts on Firefox MV2 target

### LINKED ISSUE #2183: `injectScript` never resolves in MV2
### Describe the bug

I used `injectScript` according to the documentation below. While it resolves correctly in MV3, it never resolves in MV2.

https://wxt.dev/guide/essentials/content-scripts.html#isolated-world-vs-main-world

### Reproduction

[reproduction.zip](https://github.com/user-attachments/files/25815812/reproduction.zip)

### Steps to reproduce

1. Run `pnpm install`
2. Run `pnpm dev:firefox`
3. Load the extension into Firefox.
4. Navigate to `https://www.google.com/`.
5. Open the developer tools console and verify that `Done!` is not logged.

### System Info

```shell
System:
    OS: Linux 6.6 Ubuntu 24.04.4 LTS 24.04.4 LTS (Noble Numbat)
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700F
    Memory: 20.96 GB / 23.38 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 24.14.0 - /home/nines/.volta/tools/image/node/24.14.0/bin/node
    npm: 11.11.0 - /home/nines/.volta/tools/image/npm/11.11.0/bin/npm
    pnpm: 10.30.3 - /home/nines/.volta/tools/image/pnpm/10.30.3/bin/pnpm
  npmPackages:
    wxt: ^0.20.18 => 0.20.18
```

### Used Package Manager

pnpm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://wxt.dev/guide/installation.html).
- [x] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by PatrykKuniczak**
### Overview

I've fixed issue with awaited injectScript for Firefox MV2, which isn't included in build files.

### Manual Testing

Let's try code from mentioned issue reproduction

This PR closes #2183

Code with example for that'll be merged in #2233

### CODE REVIEW

**Comment by nines75** [comment]
@PatrykKuniczak My explanation at https://github.com/wxt-dev/wxt/issues/2183#issuecomment-4192691657 was insufficient. With the current code, `injectScript` will never resolve in MV3.
What I meant was to separate the creation of the Promise via `makeLoadedPromise` from the timing of using `await` on it, just like the `injectScript` code prior to this PR.

Current code in the PR:

```ts
if (isManifestV3) {
  // Event handlers (load, error) are registered before the script execution.
  // However, since `await` is used here, it will wait forever for the `load` event to fire.
  await makeLoadedPromise(script);
}

await options?.modifyScript?.(script);

(document.head ?? document.documentElement).append(script);

if (!options?.keepInDom) {
  script.remove();
}
```

Previous code (current main branch):

```ts
// Event handlers are registered before the script execution.
// Since `await` is not used, execution doesn't pause here.
const loadedPromise = makeLoadedPromise(script);

await options?.modifyScript?.(script);

// At this point, the event handlers are guaranteed to be registered.
(document.head ?? document.documentElement).append(script);

if (!options?.keepInDom) {
  script.remove();
}

// Wait for the `load` event to fire here.
// However, the `load` event doesn't fire in MV2.
await loadedPromise;
```

Based on the above, I think it would be better to implement the fix as follows:

```ts
// Register the event handlers only for MV3.
const loadedPromise = isManifestV3 ? makeLoadedPromise(script) : undefined;

await options?.modifyScript?.(script);

(document.head ?? document.documentElement).append(script);

if (!options?.keepInDom) {
  script.remove();
}

if (isManifestV3) {
  await loadedPromise;
}
// This alternative might be better:
// if (loadedPromise) {
//   await loadedPromise;
// }
```

I'm not entirely sure if this code is perfectly correct, but I have confirmed that it works properly on Firefox MV2 and Chrome MV3.

**Comment by PatrykKuniczak** [comment]
@nines75 I was wondering, if this is necessary to do it that way, because it work's anyway.

But i've checked it, and
```ts
const loadedPromise = isManifestV3 ? makeLoadedPromise(script) : Promise.resolve();
```

works as well, we need to wait for @aklinker1 review, if we'll approve your suggestion, i'll do it, that's no problem :)

I'm not sure, my simplification is good approach 😆

File: packages/wxt/src/utils/inject-script.ts [hunk 1]
```diff
@@ -26,15 +26,22 @@ export async function injectScript(
   const url = browser.runtime.getURL(path);
   const script = document.createElement('script');
 
-  if (browser.runtime.getManifest().manifest_version === 2) {
+  const isManifestV2 = browser.runtime.getManifest().manifest_version === 2;
+  const isManifestV3 = browser.runtime.getManifest().manifest_version === 3;
```
Comment (aklinker1) [inline packages/wxt/src/utils/inject-script.ts]:
```suggestion
  const manifest = browser.runtime.getManifest()
  const isManifestV2 = manifest.manifest_version === 2;
  const isManifestV3 = manifest.manifest_version === 3;
```

File: packages/wxt/src/utils/inject-script.ts [hunk 2]
```diff
@@ -26,15 +26,22 @@ export async function injectScript(
...
     // MV3 requires using src
     script.src = url;
   }
 
-  const loadedPromise = makeLoadedPromise(script);
+  // For MV2: inline scripts execute synchronously when appended, so we don't need to wait
+  // For MV3: we need to wait for the load event
+  if (isManifestV3) {
+    await makeLoadedPromise(script);
+  }
```
Comment (aklinker1) [inline packages/wxt/src/utils/inject-script.ts]: We can't await this here. We need to create the promise before adding the script to the DOM, then await it after, like we were doing before.

```suggestion
  // For MV2: inline scripts execute synchronously when appended, so we don't need to wait
  // For MV3: we need to wait for the load event
  const loadedPromise = isManifestV3 ? makeLoadedPromise(script) : undefined;
```

Then add back the `await loadedPromise` at the bottom of the function, or wrap it in a similar if-statement.

Is this the discussion you were having above? You said this works, but that can't be true.

**Review by aklinker1 — CHANGES_REQUESTED** [review]

File: packages/wxt/src/utils/inject-script.ts (hunk 2 above)
Comment (aklinker1) [reply packages/wxt/src/utils/inject-script.ts]: Yeah, I just merged https://github.com/wxt-dev/wxt/pull/2233 and updated this branch to test against it. The current code awaits forever in MV3, doesn't work.

We need to keep awaiting it after the element is added to the DOM.

Comment (PatrykKuniczak) [reply packages/wxt/src/utils/inject-script.ts]: > Yeah, I just merged #2233 and updated this branch to test against it. The current code awaits forever in MV3, doesn't work.
> 
> We need to keep awaiting it after the element is added to the DOM.

No i see it, interesting because i've checked it before, maybe cache worked 🤔 
Thanks for second look, i'll fix it

Comment (PatrykKuniczak) [reply packages/wxt/src/utils/inject-script.ts]: @aklinker1 Should be good right now, let's check it one more time 😄

Comment (aklinker1) [reply packages/wxt/src/utils/inject-script.ts]: Why change it to `async` false?

Comment (aklinker1) [reply packages/wxt/src/utils/inject-script.ts]: Claude doesn't think setting `async` to false fixes the race condition around not adding the listeners before adding it to the dom.

**Review by aklinker1 — APPROVED** [review]
Confirmed its working with the latest changes.

File: packages/wxt/src/utils/inject-script.ts (hunk 2 above)
Comment (aklinker1) [reply packages/wxt/src/utils/inject-script.ts]: I've made the change.

**Comment by PatrykKuniczak** [comment]
@aklinker1 Yeah, that one also works.
I've previously `Promise.resolve()` on the `undefined` place, but i don't know why it wasn't work.
But it's good right now and let's leave it what it is 😄
