### PR TITLE
fix: Support negation patterns when including/excluding files from ZIP files

### LINKED ISSUE #1510: Exclude file from `.zip` with bang `!`
### Describe the bug

Asking the AI bot about excluding files from zip, I got these instructions:

```
To exclude all JSON files except manifest.json from the zip, you can configure the zip.exclude option in your wxt.config.ts file as follows:

// wxt.config.ts
import { defineConfig } from 'wxt';

export default defineConfig({
  zip: {
    exclude: [
      '**/*.json',       // Exclude all .json files
      '!manifest.json',  // Include manifest.json
    ],
  },
});

Here's how this configuration works:

    '**/*.json' excludes all files with the .json extension in any directory.
    '!manifest.json' is a negative pattern that includes manifest.json, overriding the previous exclusion.

Make sure that the paths specified in the exclude array are relative to the root of the WXT project.
```

However, the bang(!) seems to cause some weirdness when trying to open the produced zip file. 

Not sure if I'm doing something wrong, or if there is a bug?

### Reproduction

https://github.com/skube/min-repro-wxt

### Steps to reproduce

Steps:
1. `npm i`
2. `npm run zip`
3. Try to open `.zip` created in `.output/`

### System Info

```shell
System:
    OS: macOS 15.3.1
    CPU: (8) arm64 Apple M2
    Memory: 107.06 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.12.2 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
    bun: 1.2.2 - ~/.bun/bin/bun
  Browsers:
    Chrome: 133.0.6943.142
    Edge: 118.0.2088.76
    Safari: 18.3
  npmPackages:
    wxt: ^0.19.29 => 0.19.29
```

### Used Package Manager

npm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://wxt.dev/guide/installation.html).
- [x] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by nishu-murmu**
### Overview

This is issue reproduction repo: https://github.com/skube/min-repro-wxt

Here is the discussion about creating this PR and more context.

https://github.com/wxt-dev/wxt/issues/1510#issuecomment-2713315203

This PR closes #1510 

---

Edit from @aklinker1: You can now do things like this when zipping the extension and source code:

```ts
// wxt.config.ts

export default defineConfig({
  zip: {
    // Exclude all JSON files from your extension zip except for the manifest
    exclude: ["*.json", "!manifest.json"],
    // Include all TS files in your Firefox sources ZIP, except tests.
    includeSources: ["**/*.ts", "!**/__tests__/*.ts"],
    // Exclude all scripts except for a build script from Firefox sources ZIP
    excludeSources: ["scripts/*", "!scripts/build.sh"],
  },
})
```

### CODE REVIEW

**Comment by nishu-murmu** [comment]
Do I need to add some test cases for these fix?

File: packages/wxt/src/core/zip.ts [hunk 1]
```diff
@@ -121,9 +121,23 @@ async function zipDir(
...
   ).filter((relativePath) => {
+    function negateCheck() {
+      return options?.exclude?.some(
+        (option) =>
+          option.startsWith('!') && minimatch(relativePath, option.slice(1)),
+      );
+    }
+    if (negateCheck()) {
+      return true;
+    }
```
Comment (aklinker1) [inline packages/wxt/src/core/zip.ts:132]:
```suggestion
    const isNegated = options?.exclude?.some(
      (option) =>
        option.startsWith('!') && minimatch(relativePath, option.slice(1)),
    );
    if (isNegated) return true;
```

**Review by aklinker1 — CHANGES_REQUESTED** [review]
Thanks for the PR! We need to add some tests around these changes:

https://github.com/wxt-dev/wxt/blob/main/packages/wxt/e2e/tests/zip.test.ts

File: packages/wxt-demo/wxt.config.ts [hunk 2]
```diff
@@ -16,6 +16,10 @@ export default defineConfig({
   },
   zip: {
     downloadPackages: ['sass'],
+    exclude: [
+      '**/*.json', // Exclude all .json files
+      '!manifest.json', // Include manifest.json
+    ],
```
Comment (aklinker1) [inline packages/wxt-demo/wxt.config.ts:22]: Hold on, I'm looking at this code now, and based on the old logic:

```ts
options?.include?.some((pattern) => minimatch(relativePath, pattern)) || !options?.exclude?.some((pattern) => minimatch(relativePath, pattern))
```

Couldn't you have just added `mainfest.json` to `include`, since `include` has priority over `exclude`?

Comment (nishu-murmu) [reply packages/wxt-demo/wxt.config.ts:22]: Yeah, but original issue was to include this negate feature in exclude parameter. Maybe you can explain this to @skube.

Comment (nishu-murmu) [reply packages/wxt-demo/wxt.config.ts]: Oh yeah, there isn't.
that options.includes you're mentioning is taking includeSources
that is different option.
WindowsTerminal_lANMUO72n7

Comment (nishu-murmu) [reply packages/wxt-demo/wxt.config.ts]: I've added a test case.

Comment (aklinker1) [reply packages/wxt-demo/wxt.config.ts]: Ah, duh :+1:

**Review by aklinker1 — APPROVED** [review]

**Comment by aklinker1** [comment]
Sorry for the slowness, I got caught up in responding to new PRs and issues, so I lost track of this one. We'll get this merged and released now!

Gonna merge with main, checks aren't running how they should be...

**Comment by aklinker1** [comment]
One more change, I'm gonna extract this to a function and use it for both `include` and `exclude`. That way we can have unit tests to cover other cases as well.
