### PR TITLE
fix: Output main JS file for HTML entrypoints to chunks directory

### LINKED ISSUE #421: [Vite] Pre-transform error: Failed to load url /popup.js
### Describe the bug

This error up when running `pnpm dev` with the vanilla template.

```
WXT 0.16.3                                                                                                     2:04:15 PM
✔ Started dev server @ http://localhost:3000                                                                  2:04:15 PM
ℹ Pre-rendering chrome-mv3 for development with Vite 5.0.12                                                   2:04:15 PM
⠸ [2/2] popup2:04:15 PM [vite] Pre-transform error: Failed to load url /popup.js (resolved id: /popup.js). Does the file exist?
✔ Built extension in 430 ms                                                                                   2:04:15 PM
  ├─ .output/chrome-mv3/manifest.json  849 B    
  ├─ .output/chrome-mv3/popup.html     532 B    
  ├─ .output/chrome-mv3/background.js  125.66 kB
  ├─ .output/chrome-mv3/popup.js       7.43 kB  
  ├─ .output/chrome-mv3/icon/128.png   3.07 kB  
  ├─ .output/chrome-mv3/icon/16.png    559 B    
  ├─ .output/chrome-mv3/icon/32.png    916 B    
  ├─ .output/chrome-mv3/icon/48.png    1.33 kB  
  ├─ .output/chrome-mv3/icon/96.png    2.37 kB  
  └─ .output/chrome-mv3/wxt.svg        1.07 kB  
Σ Total size: 143.79 kB                                 
✔ Opened browser in 680 ms
```

It doesn't seem to break anything... Likely related to the the breaking change in `0.16.0`, where we moved the entrypoints around? Still need to do a bisect to be sure.

> "In https://github.com/wxt-dev/wxt/pull/398, HTML pages' JS entrypoints in the output directory have been moved."
>
> &ndash; https://github.com/wxt-dev/wxt/releases/tag/v0.16.0

### To Reproduce

```sh
pnpx wxt@latest init repro --pm pnpm --template vanilla
cd repro
pnpm i
pnpm dev
```

### Expected behavior

This error should not be logged.

### Screenshots

Screenshot 2024-02-05 at 2 08 40 PM

### Environment

```
  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.69 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.asdf/installs/nodejs/18.16.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.16.1/bin/yarn
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.9.0 - ~/.asdf/installs/nodejs/18.16.1/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.2.1
  npmPackages:
    wxt: ^0.16.0 => 0.16.3
```

### PR DESCRIPTION
**Pull request by aklinker1**
This closes #421 

It seems like vite logs this error when a script outside the chunks directory is mentioned in the HTML file? Not really sure why, but that was the only difference I found.

### CODE REVIEW

File: src/core/builders/vite/index.ts [hunk 1]
```diff
@@ -148,10 +154,12 @@ export async function createViteBuilder(
...
-            // Place JS entrypoints in main directory without a hash. (popup.html & popup.js are
-            // next to each other). The unique entrypoint name requirement prevents conflicts with
-            // scripts of the same name
-            entryFileNames: '[name].js',
+            entryFileNames: ({ name }) => {
+              // HTML main JS files go in the chunks folder
+              if (htmlEntrypoints.has(name)) return 'chunks/[name]-[hash].js';
+              // Scripts are output in the root folder
+              return '[name].js';
+            },
```
Comment (aklinker1) [inline src/core/builders/vite/index.ts:162]: This was the main fix. Just moving HTML entrypoints back into the chunks directory did it. This was what <=0.15 did, and there was no log.
