### PR TITLE
fix: add Firefox action manifest typings

### LINKED ISSUE #2096: Firefox: in manifest, support `default_area` and `theme_icons` in `action`
### Describe the bug

Link to docs:

- MV2 / `browser_action`:
  - [`default_area`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#:~:text=default%5Farea)
  - [`theme_icons`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#:~:text=theme%5Ficons)
- MV3 / `page_action`:
  - [`default_area`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action#:~:text=default%5Farea)
  - [`theme_icons`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action#:~:text=theme%5Ficons)

### Reproduction

From my own project:

```typescript
export default defineConfig({
  manifest: {
    […]
    action: {
      default_area: "navbar",
      theme_icons: [
        {
          dark: "tabcenter.svg",
          light: "tabcenter.svg#light",
          size: 16,
        },
        {
          dark: "tabcenter.svg",
          light: "tabcenter.svg#light",
          size: 32,
        },
      ],
      […]
    },
    […]
  },
});
```

### Steps to reproduce

Try to use `default_area` or `theme_icons` in the `action` section of a manifest.

### System Info

```shell
System:
  OS: Linux 6.18 Arch Linux
  CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
  Memory: 3.29 GB / 15.37 GB
  Container: Yes
  Shell: 5.3.9 - /usr/bin/bash
Binaries:
  Node: 25.6.0 - /run/user/1000/fnm_multishells/73650_1770598251148/bin/node
  npm: 11.8.0 - /run/user/1000/fnm_multishells/73650_1770598251148/bin/npm
  pnpm: 10.28.2 - /run/user/1000/fnm_multishells/73650_1770598251148/bin/pnpm
  Deno: 2.6.5 - /usr/bin/deno
  Watchman: 20260104.093129.0 - /usr/bin/watchman
Browsers:
  Chromium: 144.0.7559.109
  Firefox: 147.0.3
  Firefox Developer Edition: 147.0.3
npmPackages:
  wxt: ^0.20.13 => 0.20.13
```

### Used Package Manager

pnpm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://wxt.dev/guide/installation.html).
- [x] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by VaughnBosu**
### Overview

Added FirefoxActionManifestOptions interface with browser_style, default_area, and theme_icons, and applied it to action, browser_action, and page_action in UserManifest.

### Manual Testing

- pnpm test run manifest passes

- Added default_area and theme_icons to wxt-demo/wxt.config.ts — no type errors, and the values appeared in the built manifest.json

### Related Issue

This PR closes #2096

### CODE REVIEW

File: packages/wxt/src/types.ts [hunk 1]
```diff
@@ -720,6 +720,12 @@ export interface ThemeIcon {
   size: number;
 }
 
+export interface FirefoxActionManifestOptions {
+  browser_style?: boolean;
```
Comment (PatrykKuniczak) [inline packages/wxt/src/types.ts]: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles#manifest_v3_migration

This shouldn't be available for MV3.
It was removed on `Firefox 118` very old version, IMO we shouldn't support it any more.

Comment (VaughnBosu) [reply packages/wxt/src/types.ts]: Hi! 

browser_style was already on these types before my PR so I just carried it into the shared interface to keep the change as minimal as possible while fixing the issue. 

Happy to split it so action only gets default_area and theme_icons if needed

Comment (PatrykKuniczak) [reply packages/wxt/src/types.ts]: Yeah i know, that wasn't your fault, but i'm wondering if that PR is good place to do it.

But yeah, let's leave it for now and let's do it in another PR

**Review by PatrykKuniczak — APPROVED** [review]

File: packages/wxt/src/types.ts [hunk 2]
```diff
@@ -956,15 +962,11 @@ export type UserManifest = {
...
-    browser_style?: boolean;
-  };
-  page_action?: Browser.runtime.ManifestV2['page_action'] & {
-    browser_style?: boolean;
-  };
+  action?: Browser.runtime.ManifestV3['action'] & FirefoxActionManifestOptions;
+  browser_action?: Browser.runtime.ManifestV2['browser_action'] &
+    FirefoxActionManifestOptions;
+  page_action?: Browser.runtime.ManifestV2['page_action'] &
+    FirefoxActionManifestOptions;
```
Comment (aklinker1) [inline packages/wxt/src/types.ts]: Page action doesn't support `theme_icons`

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action#browser_compatibility

vs

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#browser_compatibility

Comment (aklinker1) [reply packages/wxt/src/types.ts]: > https://github.com/wxt-dev/wxt/pull/2217/changes#r3020254936

If `browser_style` isn't supported on the `action`, seems like we shouldn't create a shared type if all 3 are different.

**Review by aklinker1 — CHANGES_REQUESTED** [review]

**Review by aklinker1 — APPROVED** [review]
